# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server 


  

  
  
  
  # Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.

defaults:
  - values:
       author: "Rajiblaze"
      

      
#plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
plugins: [jekyll-paginate, jekyll-feed, jekyll-sitemap, jekyll-seo-tag]
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Habitual Gaming Network
#email: your-email@example.com
description: Gaming news, reviews, thoughts. Also some gaming hardware highlights.
# this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
 # line in _config.yml. It will appear in your document head meta (for
  #Google search results) and in your feed.xml site description.
#baseurl: "" 
# the subpath of your site, e.g. /blog
url: "https://hbgaming.net" 
# the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rajiblaze
github_username:  habitualgamer

social_name: Rajiblaze
social_links: -https://twitter.com/rajiblaze
              -https://www.facebook.com/rajiblaze/            

# Build settings
markdown: kramdown
#theme: minima
#plugins:
 
#- jekyll-sitemap
 # - jekyll-paginate
  #- jekyll-seo-tag

#google site verification
google-site-verification: google53984e88401cbf0d.html
 
  

    
#
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
