---
title: Habitual Gaming Network
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
author: Rajiblaze
paginate: 8
paginate_path: page:num
plugins:
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
description: Gaming news, reviews, thoughts. Also some gaming hardware highlights.
url: https://hbgaming.net
twitter_username: rajiblaze
github_username: habitualgamer
social_name: Rajiblaze
social_links: "-https://twitter.com/rajiblaze -https://www.facebook.com/rajiblaze/"
markdown: kramdown
google-site-verification: google53984e88401cbf0d.html
